### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by jatidevelopments** [andrenbrandao/serverless-typescript-boilerplate#1]
When I try to deploy the stack to AWS this error occurs:  

Serverless Error ---------------------------------------
 
An error occurred: HelloLambdaFunction - Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: 315573c4-9af3-4f5b-8510-ca88fee76c9b)" (RequestToken: bf35920c-274f-4231-cc75-4b7f03b76901, HandlerErrorCode: InvalidRequest).

How can I fix this?

**Comment by jatidevelopments** [comment]
Fixed with upgrading to serverless v2.68.0 and using npm instead of yarn to build deployment packages.

**Comment by andrenbrandao** [comment]
Thanks for letting me know.  I will upgrade the serverless framework. Do you think it was also a problem with yarn? Was this error happening on a local deployment or on a CI/CD pipeline?
