### ISSUE TITLE
Type 'S' does not satisfy the constraint 'JSONSchema7'

### ISSUE THREAD

**Issue by Physicliar** [andrenbrandao/serverless-typescript-boilerplate#3]
https://github.com/andrenbrandao/serverless-typescript-boilerplate/blob/6c4cdc2cce162835d5a9a5a090c12619d96d0b13/src/libs/apiGateway.ts#L9 
gives errors with the following message:
`<html>TS2344: Type 'S' does not satisfy the constraint 'JSONSchema7'.<br/>Type 'S' is not assignable to type '{ readonly [x: string]: {}; readonly $id?: string; readonly $ref?: string; readonly $schema?: string; readonly $comment?: string; readonly type?: JSONSchema7TypeName | readonly JSONSchema7TypeName[]; ... 41 more ...; readonly default?: {}; }'.`

My package versions are the following:
```
"dependencies": {
    "@middy/core": "^3.1.1",
    "@middy/http-json-body-parser": "^3.1.1",
    "@types/uuid": "^8.3.4",
    "aws-sdk": "^2.1191.0",
  },
  "devDependencies": {
    "@serverless/typescript": "^3.21.0",
    "@types/aws-lambda": "^8.10.102",
    "@types/node": "^18.6.5",
    "json-schema-to-ts": "^2.5.5",
    "serverless": "^3.21.0",
    "serverless-esbuild": "^1.32.5",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.1.0",
    "typescript": "^4.7.4"
  }
```
node version : v17.8.0
npm version: 8.16.0

**Comment by andrenbrandao** [comment]
This has to do with the version 2 you are using of `json-schema-ts`. In this boilerplate I am using version 1.

You can solve this by doing the following.

`import type { FromSchema, JSONSchema7 } from 'json-schema-to-ts';

type ValidatedAPIGatewayProxyEvent<S extends JSONSchema7> = Omit<
  APIGatewayProxyEvent,
  'body'
> & {
  body: FromSchema<S>;
};
export type ValidatedEventAPIGatewayProxyEvent<S extends JSONSchema7> = Handler<
  ValidatedAPIGatewayProxyEvent<S>,
  APIGatewayProxyResult
>;`
